### ISSUE TITLE
Crear página JSP de búsqueda

### ISSUE THREAD

**Issue by Yan90** [MapaPlus/MapaPlusWeb#1]
Crear diseño web simple pero intuitivo de búsqueda de productos o servicios, donde despliegue mediante condiciones JSTL/EL una tabla las tiendas físicas y virtuales que contienen dicho producto o servicio.

Notas:
* Crear en ruta **WEB-INF/jsp/**
* Suponer que datos vienen del controlador
* Llamar página **buscador.jsp**

**Comment by mauriciofv** [comment]
Copiado 10-4

**Comment by Yan90** [comment]
Realizado commit 26ceff104ef6e092dba6e97602ffecb32697b3ee
